#ifndef SOLO_CONF_H
#define SOLO_CONF_H

#include "contiki.h"

#ifndef SOLO_CONF_ENABLE
#define SOLO_CONF_ENABLE 0
#endif

#ifndef SOLO_CONF_PCO_ENABLE
#define SOLO_CONF_PCO_ENABLE 1
#endif 

#ifndef SOLO_CONF_CLAMPING_ENABLE
#define SOLO_CONF_CLAMPING_ENABLE 0
#endif

#ifndef SOLO_CONF_INTERVAL
#define INTERVAL (32 * CLOCK_SECOND)
#define BEACON_INTERVAL INTERVAL 
#endif

#ifndef SOLO_CONF_INTERVAL_THRESHOLD
#define SOLO_CONF_INTERVAL_THRESHOLD (2*INTERVAL)
#endif

#ifndef SOLO_CONF_TIMESTAMP_THRESHOLD
#define SOLO_CONF_TIMESTAMP_THRESHOLD (4*INTERVAL)
#endif

#ifndef SOLO_CONF_BETA
#define SOLO_CONF_BETA 20
#endif 

#endif
