#define WITH_TINYOS_AUTO_IDS 1

#define SOLO_CONF_ENABLE 1
#define SOLO_CONF_PCO_ENABLE 1
#define SOLO_CONF_CLAMPING_ENABLE 1
#define SOLO_CONF_LOOP_DETECT_ENABLE 1

#define CC2420_CONF_SFD_TIMESTAMPS 1

